CarStation.Presentation/Models/BranchOffice.cs
using System;
using AutoMapper;
using CarStation.Domain.Models;

namespace CarStation.Presentation.Models
{
    /// <summary>
    /// Branch office domain model
    /// </summary>
    public class BranchOffice
    {
        /// <summary>
        /// _id
        /// </summary>
        public Guid _id { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Street
        /// </summary>
        public string Street { get; set; }

        /// <summary>
        /// Location id
        /// </summary>
        public Guid LocationId { get; set; }

        /// <summary>
        /// Location
        /// </summary>
        public string LocationName { get; set; }

        /// <summary>
        /// Telephone number
        /// </summary>
        public string Telephone { get; set; }
    }

    public class BranchOfficeMapper
    {
        public IMapper EntityMapper;

        public BranchOfficeMapper()
        {
            var entityConfig = new MapperConfiguration(cfg => cfg.CreateMap<BranchOfficeDomainModel, BranchOffice>());

            EntityMapper = entityConfig.CreateMapper();
        }

    }
}

CarStation.Presentation/Controllers/BranchOfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using CarStation.Domain.Models;
using CarStation.Domain.Services;
using CarStation.Presentation.Models;
using BranchOffice = CarStation.Presentation.Models.BranchOffice;

namespace CarStation.Presentation.Controllers
{
    public class BranchOfficeController : Controller
    {
        private readonly IBranchOfficeService _branchOfficeService;
        private readonly ILocationService _locationService;
        private readonly BranchOfficeMapper _branchOfficeMapper;
        private readonly ICountryService _countryService;
        private ICurrencyService _currencyService;

        public BranchOfficeController(IBranchOfficeService branchOfficeService, ILocationService locationService, BranchOfficeMapper branchOfficeMapper, ICountryService countryService, ICurrencyService currencyService)
        {
            _branchOfficeService = branchOfficeService;
            _locationService = locationService;
            _branchOfficeMapper = branchOfficeMapper;
            _countryService = countryService;
            _currencyService = currencyService;
        }

        /// <summary>
        /// Prikazuje listu filijala.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [Authorize]
        public ActionResult Index()
        {
            var branchDomainModels = _branchOfficeService.GetAll();
            var offices = _branchOfficeMapper.EntityMapper.Map<IList<BranchOffice>>(branchDomainModels);
            foreach (var branchOffice in offices)
            {
                branchOffice.LocationName = _locationService.GetById(branchOffice.LocationId).Name;
            }
            return View(offices);
        }

        [HttpGet]
        public JsonResult GetByCity(Guid ID)
        {
            var branchOffices = _branchOfficeService.GetByCity(ID);

            var model = branchOffices.Select(x =>
                        new
                        {
                            id = x._id.ToString(),
                            text = x.Name
                        });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Prikazuje formu za unos nove filijale.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Create()
        {
            var locations = _locationService.GetAll();
            ViewBag.Gradovi = locations.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        });

            var countries = _countryService.GetAll();
            ViewBag.Drzave = countries.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}" 
                        });
            var currencies = _currencyService.GetAll();
            ViewBag.Valute = currencies.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}"
                        });
            return View();
        }

        /// <summary>
        /// Kreira novu filijalu.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Create(BranchOfficeDomainModel model)
        {
            if (ModelState.IsValid)
            {
                var existingBranchOffice = _branchOfficeService.GetByName(model.Name);

                if(existingBranchOffice != null)
                {
                    ModelState.AddModelError("", "Filijala sa unešenim Nameom već postoji.");
                }
                else
                {
                    _branchOfficeService.Save(model);
                    return RedirectToAction("Index");
                }
            }

            var locations = _locationService.GetAll();
            ViewBag.Gradovi = locations.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        }); 

            return View(model);
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje filijale.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Edit(Guid ID)
        {
            var locations = _locationService.GetAll();
            ViewBag.Gradovi = locations.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        });

            var countries = _countryService.GetAll();
            ViewBag.Drzave = countries.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}"
                        });
            var currencies = _currencyService.GetAll();
            ViewBag.Valute = currencies.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}"
                        });

            var branchOffice = _branchOfficeService.GetById(ID);

            return View(branchOffice);
        }

        /// <summary>
        /// Ažurira postojeću filijalu.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Edit(BranchOfficeDomainModel model)
        {
            if (!ModelState.IsValid) return View(model);

            _branchOfficeService.Update(model);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Briše filijalu prema njenom ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        public JsonResult Delete(Guid ID)
        {
            var branchOffice = _branchOfficeService.GetById(ID);
            _branchOfficeService.Delete(branchOffice._id);

            return Json("OK");
        }

        /// <summary>
        /// Prikazuje promet prema filijalama.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public JsonResult GetNumberOfRentsByBranchOffice()
        {
            var filijale = _branchOfficeService.GetNumberOfRentsByBranchOffice();
            return Json(filijale, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLocationCurrency(Guid officeId)
        {
            var office = _branchOfficeService.GetById(officeId);
            var location = _locationService.GetById(office.LocationId);
            var currency = _currencyService.GetById(location.CurrencyId);

            return Json(currency.symbol_native, JsonRequestBehavior.AllowGet);
        }
    }
}

CarStation.Presentation/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarStation.Domain.Models;
using CarStation.Domain.Services;
using CarStation.Presentation.Models;

namespace CarStation.Presentation.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILocationService _locationService;
        private readonly LocationMapper _locationMapper;
        private readonly ICountryService _countryService;
        private readonly ICurrencyService _currencyService;

        public LocationController(ILocationService locationService, LocationMapper locationMapper, ICountryService countryService, ICurrencyService currencyService)
        {
            _locationService = locationService;
            _locationMapper = locationMapper;
            _countryService = countryService;
            _currencyService = currencyService;
        }

        /// <summary>
        /// Prikazuje listu gradova.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        public ActionResult Index()
        {
            var locationDomainModels = _locationService.GetAll();

            var locations = _locationMapper.EntityMapper.Map<IList<Location>>(locationDomainModels);

            foreach (var location in locations)
            {
                location.Country = _countryService.GetById(location.CountryId).name;
                location.Currency = $"{_currencyService.GetById(location.CurrencyId).name} ({_currencyService.GetById(location.CurrencyId).code})";
            }

            return View(locations);
        }

        /// <summary>
        /// Prikazuje formu za kreiranje novog lokacije.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Create()
        {
            var countries = _countryService.GetAll();
            ViewBag.Drzave = countries.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}"
                        });
            var currencies = _currencyService.GetAll();
            ViewBag.Valute = currencies.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}"
                        });
            return View();
        }

        /// <summary>
        /// Kreira novi Location.
        /// </summary>
        /// <param name="isModal"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Create(bool? isModal, LocationDomainModel model)
        {
            if (ModelState.IsValid)
            {
                if(_locationService.GetByName(model.Name) != null)
                {
                    ModelState.AddModelError("", "Unešena lokacija već postoji.");
                    return View(model);
                }
                _locationService.Save(model);
                return isModal.HasValue ? (ActionResult) Json("OK") : RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje postojećeg lokacije.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Edit(Guid ID)
        {
            var countries = _countryService.GetAll();
            ViewBag.Drzave = countries.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}"
                        });
            var currencies = _currencyService.GetAll();
            ViewBag.Valute = currencies.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({x.code})  {x.name}"
                        });
            var location = _locationService.GetById(ID);
            return View(location);
        }

        /// <summary>
        /// Ažurira postojeći Location.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Edit(LocationDomainModel model)
        {
            if (ModelState.IsValid)
            {
                _locationService.Update(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// Briše Location prema ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        public JsonResult Delete(Guid ID)
        {
            _locationService.Delete(ID);

            return Json("OK");
        }
    }
}

CarStation.Presentation/Views/BranchOffice/Create.cshtml
@model CarStation.Domain.Models.BranchOfficeDomainModel
@{
    ViewBag.Title = "Nova filijala";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        PorukeValidacija();

        $('#GradLista').select2({ placeholder: "Izaberite lokacija..." });
        $('#DrzavaLista').select2({ placeholder: "Izaberite državu..." });
        $('#ValutaLista').select2({ placeholder: "Izaberite valutu..." });

        $('#novi-Location').click(function (e) {
            e.preventDefault();
            
            $.ajax({
                type: "POST",
                url: "@Url.Action("Create", "Location")",
                data: JSON.stringify({
                    isModal: true,
                    Name: $('#Location-Name').val(),
                    CountryId: $('#DrzavaLista').val(),
                    CurrencyId: $('#ValutaLista').val(),
                    Tax: $('#Tax').val()
                }),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat == "OK") {
                        location.reload();
                    }
                    else {
                        alert("Došlo je do greške prilikom čuvanja lokacije.");
                    }

                }
            });
        });

        $("#forma-filijala").validate({
            rules: {
                Name: {
                    required: true,
                    minlength: 2
                },
                Street: {
                    required: true,
                    minlength: 2
                },
                Telephone: {
                    required: true,
                    minlength: 6,
                    digits: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });

</script>
<style>
    .select2.select2-container {
        width: 280px !important;
    }
</style>
<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Create", "BranchOffice", FormMethod.Post, new { @id = "forma-filijala" }))
        {
            <span class="error">@Html.ValidationSummary(true, "Čuvanje filijale nije uspjelo.")</span>
            <div>
                <fieldset>
                    <legend>Detalji filijale</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Name</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Name, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Street</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Street, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Street, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Lokacija</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.LocationId, (IEnumerable<SelectListItem>)ViewBag.Gradovi, new { @id = "GradLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.LocationId, null, new { @class = "inline-help error" })
                                <!-- Aktiviraj proizvođači modal -->
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#Location-modal">
                                    <i class="glyphicon glyphicon-plus"></i> Dodaj lokaciju
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Broj telefona</label>
                            </div>
                            <div class="editor-field">
                                <i class="glyphicon glyphicon-phone"></i> <span id="pozivni-za-Location"></span>
                                @Html.TextBoxFor(u => u.Telephone, new { @class = "form-control", @type = "number" })
                                @Html.ValidationMessageFor(u => u.Telephone, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "BranchOffice", null, new { @class = "btn btn-default" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

@*Modal lokacije*@
<div class="modal fade" id="Location-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Novi Location</h4>
            </div>
            <div class="modal-body">
                <form method="post" name="NoviGrad" id="forma-lokacije">
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Name</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Name" id="Location-Name" class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Država</label>
                        </div>
                        <div class="editor-field">
                            @Html.DropDownList("CountryId", (IEnumerable<SelectListItem>) ViewBag.Drzave, new {@id = "DrzavaLista", @class = "form-control"})
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Valuta</label>
                        </div>
                        <div class="editor-field">
                            @Html.DropDownList("CurrencyId", (IEnumerable<SelectListItem>)ViewBag.Valute, new { @id = "ValutaLista", @class = "form-control" })
                            @Html.ValidationMessage("CurrencyId", null, new { @class = "inline-help error" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Porez (%)</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Name" id="Tax" class="form-control" />
                            @Html.ValidationMessage("Tax", null, new { @class = "inline-help error" })
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                <button type="button" id="novi-Location" class="btn btn-primary">Sačuvaj</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

CarStation.Presentation/Views/BranchOffice/Edit.cshtml
@model CarStation.Domain.Models.BranchOfficeDomainModel
@{
    ViewBag.Title = "Uredi filijalu";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
       PorukeValidacija();

        $('#GradLista').select2({ placeholder: "Izaberite lokacija..." });
        $('#DrzavaLista').select2({ placeholder: "Izaberite državu..." });
        $('#ValutaLista').select2({ placeholder: "Izaberite valutu..." });

        $('#novi-Location').click(function (e) {
            e.preventDefault();

            $.ajax({
                type: "POST",
                url: "@Url.Action("Create", "Location")",
                data: JSON.stringify({
                    isModal: true,
                    Name: $('#Location-Name').val(),
                    CountryId: $('#DrzavaLista').val(),
                    CurrencyId: $('#ValutaLista').val(),
                    Tax: $('#Tax').val()
                }),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat == "OK") {
                        location.reload();
                    }
                    else {
                        alert("Došlo je do greške prilikom čuvanja lokacije.");
                    }

                }
            });
        });

        $("#forma-filijala").validate({
            rules: {
                Name: {
                    required: true,
                    minlength: 2
                },
                Street: {
                    required: true,
                    minlength: 2
                },
                Telephone: {
                    required: true,
                    minlength: 6,
                    maxlength: 7,
                    digits: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });

</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Edit", "BranchOffice", FormMethod.Post, new { @id = "forma-filijala" }))
        {
            @Html.ValidationSummary(true, "Čuvanje filijale nije uspjelo.");
            <div>
                @Html.HiddenFor(u => u._id)
                <fieldset>
                    <legend>Detalji filijale</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Name</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Name, new {@class = "form-control", @readonly = ""})
                                @Html.ValidationMessageFor(u => u.Name, null, new {@class = "inline-help error"})
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Street</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Street, new {@class = "form-control"})
                                @Html.ValidationMessageFor(u => u.Street, null, new {@class = "inline-help error"})
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Location</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.LocationId, (IEnumerable<SelectListItem>) ViewBag.Gradovi, new {@id = "GradLista", @class = "form-control"})
                                @Html.ValidationMessageFor(u => u.LocationId, null, new {@class = "inline-help error"})
                                <!-- Aktiviraj proizvođači modal -->
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#Location-modal">
                                    <i class="glyphicon glyphicon-plus"></i> Dodaj lokacija
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Broj telefona</label>
                            </div>
                            <div class="editor-field">
                                <i class="glyphicon glyphicon-phone"></i> <span id="pozivni-za-Location"></span>
                                @Html.TextBoxFor(u => u.Telephone, new {@class = "form-control", @type = "number"})
                                @Html.ValidationMessageFor(u => u.Telephone, null, new {@class = "inline-help error"})
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj"/>
                        @Html.ActionLink("Odustani", "Index", "BranchOffice", null, new {@class = "btn btn-default"})
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

@*Modal lokacije*@
<div class="modal fade" id="Location-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Novi Location</h4>
            </div>
            <div class="modal-body">
                <form method="post" name="NoviGrad" id="forma-lokacije">
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Name</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Name" id="Location-Name" class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Država</label>
                        </div>
                        <div class="editor-field">
                            @Html.DropDownList("CountryId", (IEnumerable<SelectListItem>)ViewBag.Drzave, new { @id = "DrzavaLista", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Valuta</label>
                        </div>
                        <div class="editor-field">
                            @Html.DropDownList("CurrencyId", (IEnumerable<SelectListItem>)ViewBag.Valute, new { @id = "ValutaLista", @class = "form-control" })
                            @Html.ValidationMessage("CurrencyId", null, new { @class = "inline-help error" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Porez (%)</label>
                        </div>
                        <div class="editor-field">
                            @Html.TextBox("Tax", new { @class = "form-control", @type = "number" })
                            @Html.ValidationMessage("Tax", null, new { @class = "inline-help error" })
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                <button type="button" id="novi-Location" class="btn btn-primary">Sačuvaj</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->