CarStation.Presentation/Models/VehicleModel.cs
using System;
using AutoMapper;
using CarStation.Domain.Models;
using CarStation.Domain.Models.Enums;

namespace CarStation.Presentation.Models
{
    /// <summary>
    /// VehicleModel model
    /// </summary>
    public class VehicleModel
    {

        public Guid _id { get; set; }
        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Number of passengers
        /// </summary>
        public int Passengers { get; set; }

        /// <summary>
        /// Indicates if vehicle has automatic transmission
        /// </summary>
        public bool IsAutomatic { get; set; }

        /// <summary>
        /// Manufacturer id
        /// </summary>
        public Guid ManufacturerId { get; set; }
        public string Manufacturer { get; set; }

        /// <summary>
        /// Type of fuel
        /// </summary>
        public Fuel Fuel { get; set; } = Fuel.Diesel;

        /// <summary>
        /// Type of vehicle
        /// </summary>
        public VehicleType Type { get; set; } = VehicleType.Compact;

        /// <summary>
        /// Status
        /// </summary>
        public VehicleStatus Status { get; set; } = VehicleStatus.Available;
    }

    public class VehicleModelMapper
    {
        public IMapper EntityMapper;

        public VehicleModelMapper()
        {
            var entityConfig = new MapperConfiguration(cfg => cfg.CreateMap<VehicleModelDomainModel, VehicleModel>());

            EntityMapper = entityConfig.CreateMapper();
        }

    }
}

CarStation.Presentation/Controllers/ManufacturerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarStation.Domain.Models;
using CarStation.Domain.Services;
using CarStation.Presentation.Models;

namespace CarStation.Presentation.Controllers
{
    public class ManufacturerController : Controller
    {
        private readonly IManufacturerService _manufacturerService;
        private readonly ManufacturerMapper _manufacturerMapper;

        public ManufacturerController(IManufacturerService manufacturerService, ManufacturerMapper manufacturerMapper)
        {
            _manufacturerService = manufacturerService;
            _manufacturerMapper = manufacturerMapper;
        }

        /// <summary>
        /// Prikazuje listu proizvođača.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        public ActionResult Index()
        {
            var manufacturerDomainModels = _manufacturerService.GetAll();
            var manufacturers = _manufacturerMapper.EntityMapper.Map<IList<Manufacturer>>(manufacturerDomainModels);
            return View(manufacturers);
        }

        /// <summary>
        /// Prikazuje formu za unos novog proizvođača.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Kreira novog proizvođača.
        /// </summary>
        /// <param name="isModal"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Create(bool? isModal, ManufacturerDomainModel model)
        {
            if (ModelState.IsValid)
            {
                if(_manufacturerService.GetByName(model.Name) != null)
                {
                    ModelState.AddModelError("", "Unešeni proizvođač već postoji");
                    return View(model);
                }

                _manufacturerService.Save(model);

                return isModal.HasValue && isModal.Value
                    ? (ActionResult) Json("OK")
                    : RedirectToAction("Index", "Vehicle");
            }
            return View(model);
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje postojećeg proizvođača.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Edit(Guid ID)
        {
            var model = _manufacturerService.GetById(ID);
            return View(model);
        }

        /// <summary>
        /// Ažurira postojećeg proizvođača.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Edit(ManufacturerDomainModel model)
        {
            if (ModelState.IsValid)
            {
                if (_manufacturerService.GetById(model._id).Logo != null && model.Logo != null)
                    DeleteLogo(_manufacturerService.GetById(model._id).Logo);

                _manufacturerService.Update(model);
                return RedirectToAction("Index", "Vehicle");
            }
            return View(model);
        }

        /// <summary>
        /// Briše proizvođača prema ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        public JsonResult Delete(Guid ID)
        {
            var manufacturer = _manufacturerService.GetById(ID);
            _manufacturerService.Delete(ID);

            if (manufacturer.Logo != null)
                DeleteLogo(manufacturer.Logo);

            return Json("OK");
        }

        /// <summary>
        /// Čuva logo za traženog proizvođača.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public JsonResult SavePicture()
        {
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var file = Request.Files[i];

                var fileName = Path.GetFileName(file.FileName);
                var path = "/Slike/Proizvodjaci/" + fileName;
                var fullPath = Server.MapPath(path);
                file.SaveAs(fullPath);

                return Json(path, JsonRequestBehavior.AllowGet);
            }
            return Json("ERROR");
        }

        /// <summary>
        /// Briše logo za traženog proizvođača.
        /// </summary>
        /// <param name="Logo"></param>
        [CustomAuthorization]
        [HttpPost]
        public void DeleteLogo(string Logo)
        {
            string fullPath = Request.MapPath(Logo);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
        }
    }
}

CarStation.Presentation/Controllers/VehicleModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarStation.Domain.Models;
using CarStation.Domain.Models.Enums;
using CarStation.Domain.Services;
using CarStation.Presentation.Models;

namespace CarStation.Presentation.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly IVehicleModelService _vehicleModelService;
        private readonly IManufacturerService _manufacturerService;
        private readonly VehicleModelMapper _vehicleModelMapper;

        public VehicleModelController(IVehicleModelService vehicleModelService, IManufacturerService manufacturerService, VehicleModelMapper vehicleModelMapper)
        {
            _vehicleModelService = vehicleModelService;
            _manufacturerService = manufacturerService;
            _vehicleModelMapper = vehicleModelMapper;
        }

        /// <summary>
        /// Prikazuje listu modela vozila.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        public ActionResult Index()
        {
            var vehicleModelDomainModels = _vehicleModelService.GetAll();
            var vehicleModels = _vehicleModelMapper.EntityMapper.Map<IList<VehicleModel>>(vehicleModelDomainModels);
            foreach (var vehicleModel in vehicleModels)
            {
                vehicleModel.Manufacturer = _manufacturerService.GetById(vehicleModel.ManufacturerId).Name;
            }
            return View(vehicleModels);
        }

        /// <summary>
        /// Prikazuje formu za unos novog modela vozila.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Create()
        {
            var manufacturers = _manufacturerService.GetAll();
            var vehicleTypes = Enum.GetValues(typeof(VehicleType)).Cast<VehicleType>().ToList(); 
            var fuels = Enum.GetValues(typeof(Fuel)).Cast<Fuel>().ToList();

            ViewBag.Proizvodjaci = manufacturers.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        });

            ViewBag.TipoviVozila = vehicleTypes.Select(x =>
                        new SelectListItem
                        {
                            Value = ((int)x).ToString(),
                            Text = x.ToString()
                        });

            ViewBag.TipoviGoriva = fuels.Select(x =>
                        new SelectListItem
                        {
                            Value = ((int)x).ToString(),
                            Text = x.ToString()
                        }); 
            return View();
        }

        /// <summary>
        /// Kreira novi model vozila.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Create(VehicleModelDomainModel model)
        {
            if (ModelState.IsValid)
            {
                if(_vehicleModelService.GetByName(model.Name) != null)
                {
                    ModelState.AddModelError("", "Unešeni model vozila već postoji.");
                }
                else
                {
                    _vehicleModelService.Save(model);
                    return RedirectToAction("Index", "Vehicle");
                }
                
            }

            var manufacturers = _manufacturerService.GetAll();
            var vehicleTypes = Enum.GetValues(typeof(VehicleType)).Cast<VehicleType>().ToList();
            var fuels = Enum.GetValues(typeof(Fuel)).Cast<Fuel>().ToList();

            ViewBag.Proizvodjaci = manufacturers.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        });

            ViewBag.TipoviVozila = vehicleTypes.Select(x =>
                        new SelectListItem
                        {
                            Value = ((int)x).ToString(),
                            Text = x.ToString()
                        });

            ViewBag.TipoviGoriva = fuels.Select(x =>
                        new SelectListItem
                        {
                            Value = ((int)x).ToString(),
                            Text = x.ToString()
                        });

            return View(model);
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje postojećeg vozila.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Edit(Guid ID)
        {
            var manufacturers = _manufacturerService.GetAll();
            var vehicleTypes = Enum.GetValues(typeof(VehicleType)).Cast<VehicleType>().ToList();
            var fuels = Enum.GetValues(typeof(Fuel)).Cast<Fuel>().ToList();

            ViewBag.Proizvodjaci = manufacturers.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        });

            ViewBag.TipoviVozila = vehicleTypes.Select(x =>
                        new SelectListItem
                        {
                            Value = ((int)x).ToString(),
                            Text = x.ToString()
                        });

            ViewBag.TipoviGoriva = fuels.Select(x =>
                        new SelectListItem
                        {
                            Value = ((int)x).ToString(),
                            Text = x.ToString()
                        });

            var model = _vehicleModelService.GetById(ID);

            return View(model);
        }

        /// <summary>
        /// Ažurira postojeći model vozila.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpPost]
        public ActionResult Edit(VehicleModelDomainModel model)
        {
            if (ModelState.IsValid)
            {
                _vehicleModelService.Update(model);
                return RedirectToAction("Index", "Vehicle");
            }
            return View(model);
        }

        /// <summary>
        /// Briše model vozila prema ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        public JsonResult Delete(Guid ID)
        {
            _vehicleModelService.Delete(ID);

            return Json("OK");
        }

    }
}

CarStation.Presentation/Views/VehicleModel/Create.cshtml
@model CarStation.Domain.Models.VehicleModelDomainModel
@{
    ViewBag.Title = "Novi model vozila";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        PorukeValidacija();

        $("#forma-model-vozila").validate({
            rules: {
                Name: {
                    required: true,
                    minlength: 2
                },
                Passengers: {
                    required: true,
                    number: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });

        $('#TipVozilaLista').select2({ placeholder: "Izaberite tip vozila..." });
        $('#ProizvodjacLista').select2({ placeholder: "Izaberite proizvodjaca..." });
        $('#TipGorivaLista').select2({ placeholder: "Izaberite tip goriva..." });

        $('#novi-proizvodjac').click(function (e) {
            e.preventDefault();

            $.ajax({
                type: "POST",
                url: "@Url.Action("Create", "Manufacturer")",
                data: JSON.stringify({
                    isModal: true,
                    Name: $('#proizvodjac-Name').val(),
                    Logo: $('#proizvodjac-logo').val()
                }),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat == "OK") {
                        location.reload();
                    }
                    else {
                        alert("Došlo je do greške prilikom čuvanja proizvođača.");
                    }

                }
            });
        });
    });

</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Create", "VehicleModel", FormMethod.Post, new { @id = "forma-model-vozila" }))
        {
            <span class="error">@Html.ValidationSummary(true, "Čuvanje modela vozila nije uspjelo.")</span>
            <div>
                <fieldset>
                    <legend>Detalji</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Naziv</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Name, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                                <label>@Html.CheckBoxFor(m => m.IsAutomatic) Automatik?</label>
                                @Html.ValidationMessageFor(u => u.IsAutomatic, null, new { @class = "inline-help error" })
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Broj osoba</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Passengers, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Passengers, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Proizvođač</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.ManufacturerId, (IEnumerable<SelectListItem>)ViewBag.Proizvodjaci, new { @id = "ProizvodjacLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.ManufacturerId, null, new { @class = "inline-help error" })
                                <!-- Aktiviraj proizvođači modal -->
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#proizvodjac-modal">
                                    <i class="glyphicon glyphicon-plus"></i> Dodaj proizvođača
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Tip vozila</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.Type, (IEnumerable<SelectListItem>)ViewBag.TipoviVozila, new { @id = "TipVozilaLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Type, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Tip goriva</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.Fuel, (IEnumerable<SelectListItem>)ViewBag.TipoviGoriva, new { @id = "TipGorivaLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Fuel, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "Vehicle", null, new { @class = "btn btn-default" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

@*Modal proizvođača*@
<div class="modal fade" id="proizvodjac-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Novi proizvođač</h4>
            </div>
            <div class="modal-body">
                <form method="post" name="NoviProizvodjac" id="forma-proizvodjac">
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Naziv</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Name" id="proizvodjac-Name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Logo</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Logo" id="proizvodjac-logo" class="form-control" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                <button type="button" id="novi-proizvodjac" class="btn btn-primary">Sačuvaj</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

CarStation.Presentation/Views/VehicleModel/Edit.cshtml
@model CarStation.Domain.Models.VehicleModelDomainModel
@{
    ViewBag.Title = "Uredi model vozila";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        PorukeValidacija();

        $("#forma-model-vozila").validate({
            rules: {
                Name: {
                    required: true,
                    minlength: 2
                },
                Passengers: {
                    required: true,
                    number: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });

        $('#TipVozilaLista').select2({ placeholder: "Izaberite tip vozila..." });
        $('#ProizvodjacLista').select2({ placeholder: "Izaberite proizvodjaca..." });
        $('#TipGorivaLista').select2({ placeholder: "Izaberite tip goriva..." });

        $('#novi-proizvodjac').click(function (e) {
            e.preventDefault();

            $.ajax({
                type: "POST",
                url: "@Url.Action("Create", "Manufacturer")",
                data: JSON.stringify({
                    isModal: true,
                    Name: $('#proizvodjac-Name').val(),
                    Logo: $('#proizvodjac-logo').val()
                }),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat == "OK") {
                        location.reload();
                    }
                    else {
                        alert("Došlo je do greške prilikom čuvanja proizvođača.");
                    }

                }
            });
        });
    });

</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Edit", "VehicleModel", FormMethod.Post, new { @id = "forma-model-vozila" }))
        {
            @Html.ValidationSummary(true, "Čuvanje modela vozila nije uspjelo.");
            <div>
                @Html.HiddenFor(u => u._id)
                <fieldset>
                    <legend>Detalji modela vozila</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Name</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Name, new {@class = "form-control", @readonly = ""})
                                @Html.ValidationMessageFor(u => u.Name, null, new {@class = "inline-help error"})
                            </div>
                        </div>
                        <div class="form-group">
                            <label>@Html.CheckBoxFor(m => m.IsAutomatic) Automatik?</label>
                            @Html.ValidationMessageFor(u => u.IsAutomatic, null, new {@class = "inline-help error"})
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Broj osoba</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Passengers, new {@class = "form-control"})
                                @Html.ValidationMessageFor(u => u.Passengers, null, new {@class = "inline-help error"})
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Proizvođač</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.ManufacturerId, (IEnumerable<SelectListItem>) ViewBag.Proizvodjaci, new {@id = "ProizvodjacLista", @class = "form-control"})
                                @Html.ValidationMessageFor(u => u.ManufacturerId, null, new {@class = "inline-help error"})
                                <!-- Aktiviraj proizvođači modal -->
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#proizvodjac-modal">
                                    <i class="glyphicon glyphicon-plus"></i> Dodaj proizvođača
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Tip vozila</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.Type, (IEnumerable<SelectListItem>) ViewBag.TipoviVozila, new {@id = "TipVozilaLista", @class = "form-control"})
                                @Html.ValidationMessageFor(u => u.Type, null, new {@class = "inline-help error"})
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Tip goriva</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.Fuel, (IEnumerable<SelectListItem>) ViewBag.TipoviGoriva, new {@id = "TipGorivaLista", @class = "form-control"})
                                @Html.ValidationMessageFor(u => u.Fuel, null, new {@class = "inline-help error"})
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj"/>
                        @Html.ActionLink("Odustani", "Index", "Vehicle", null, new {@class = "btn btn-default"})
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

@*Modal proizvođača*@
<div class="modal fade" id="proizvodjac-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Novi proizvođač</h4>
            </div>
            <div class="modal-body">
                <form method="post" name="NoviProizvodjac" id="forma-proizvodjac">
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Name</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Name" id="proizvodjac-Name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Logo</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Logo" id="proizvodjac-logo" class="form-control" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                <button type="button" id="novi-proizvodjac" class="btn btn-primary">Sačuvaj</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->