CarStation.Presentation/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarStation.Domain.Models;
using CarStation.Domain.Services;
using CarStation.Presentation.Models;

namespace CarStation.Presentation.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;
        private readonly IRentService _rentService;
        private readonly ClientMapper _clientMapper;

        public ClientController(IClientService clientService, IRentService rentService, ClientMapper clientMapper)
        {
            _clientService = clientService;
            _rentService = rentService;
            _clientMapper = clientMapper;
        }

        /// <summary>
        /// Prikazuje listu klijenata.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        public ActionResult Index()
        {
            var clientDomainModels = _clientService.GetAll();
            var clients = _clientMapper.EntityMapper.Map<IList<Client>>(clientDomainModels);
            return View(clients);
        }

        /// <summary>
        /// Prikazuje formu za kreiranje novog klijenta.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            var model = new ClientDomainModel();
            return View(model);
        }

        /// <summary>
        /// Kreira novog klijenta.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Create(ClientDomainModel model)
        {
            if (ModelState.IsValid)
            {
                if (_clientService.GetByEmail(model.Email) != null)
                {
                    return Json("ERROR_POSTOJI");
                }
                else
                {
                    _clientService.Save(model);
                    return Json("OK");
                }
            }
            return Json("ERROR");
        }

        /// <summary>
        /// Prikazuje formu za uređivanje klijentskog naloga.
        /// </summary>
        /// <param name="Email"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(string Email)
        {
            var client = _clientService.GetByEmail(Email);
            ViewBag.Zakupi = _rentService.GetRentsByClient(client._id);

            var model = new ClientDomainModel
            {
                Name = client.Name,
                Email = client.Email,
                DrivingLicence = client.DrivingLicence,
                IdentityCard = client.IdentityCard,
                Telephone = client.Telephone
            };

            return View(model);

        }

        /// <summary>
        /// Ažurira klijentski nalog.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(ClientDomainModel model)
        {
            if (ModelState.IsValid)
            {
                _clientService.Update(model);
                return Json("OK");
            }
            return View();
        }

        /// <summary>
        /// Prikazuje detalje traženog klijenta.
        /// </summary>
        /// <param name="Email"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult Details(string Email)
        {
            var clientDomainModel = _clientService.GetByEmail(Email);
            var client = _clientMapper.EntityMapper.Map<Client>(clientDomainModel);

            return client != null ? Json(client, JsonRequestBehavior.AllowGet) : Json("ERROR");
        }

        /// <summary>
        /// Briše klijenta prema ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [CustomAuthorization]
        public JsonResult Delete(Guid ID)
        {
            _clientService.Delete(ID);

            return Json("OK");
        }
    }
}

CarStation.Presentation/Controllers/HomeController.cs
using CarStation.Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarStation.Domain.Services;

namespace CarStation.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRentService _rentService;
        private readonly ILocationService _locationService;
        private readonly ICountryService _countryService;
        private readonly IBranchOfficeService _branchOfficeService;
        private readonly BranchOfficeMapper _branchOfficeMapper;

        public HomeController(IRentService rentService, ILocationService locationService, BranchOfficeMapper branchOfficeMapper, 
            IBranchOfficeService branchOfficeService, ICountryService countryService)
        {
            _rentService = rentService;
            _locationService = locationService;
            _branchOfficeMapper = branchOfficeMapper;
            _branchOfficeService = branchOfficeService;
            _countryService = countryService;
        }

        /// <summary>
        /// Prikazuje listu gradova.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var locations = _locationService.GetAll();
            ViewBag.Gradovi = locations.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = $"({_countryService.GetById(x.CountryId).code}) {x.Name}"
                        }).OrderBy(x => x.Text);
            return View();
        }

        /// <summary>
        /// Prikazuje stranicu o nama.
        /// </summary>
        /// <returns></returns>
        public ActionResult About()
        {   
            return View();
        }

        /// <summary>
        /// Prikazuje kontakt stranicu.
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            var officeDomainModels = _branchOfficeService.GetAll();
            var offices = _branchOfficeMapper.EntityMapper.Map<IList<BranchOffice>>(officeDomainModels);
            foreach (var office in offices)
            {
                office.LocationName = _locationService.GetById(office.LocationId).Name;
            }
            ViewBag.Filijale = offices;

            return View();
        }

        /// <summary>
        /// Prikazuje kontrolnu tablu.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public ActionResult Dashboard()
        {
            return View();
        }

        /// <summary>
        /// Statistički prikaz zakupa po mjesecima.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        [HttpGet]
        public JsonResult RentStatistics()
        {
            var rents = _rentService.GetByMonth();
            return Json(rents, JsonRequestBehavior.AllowGet);
        }
    }
}

CarStation.Presentation/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security;
using System.Security.Permissions;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CarStation.Domain.Models;
using CarStation.Domain.Models.Enums;
using CarStation.Domain.Services;
using CarStation.Presentation.Models;
using Microsoft.Reporting.WebForms;

namespace CarStation.Presentation.Controllers
{
    public class RentController : Controller
    {
        private readonly IRentService _rentService;
        private readonly ILocationService _locationService;
        private readonly IClientService _clientService;
        private readonly IBranchOfficeService _branchOfficeService;
        private readonly IVehicleService _vehicleService;
        private readonly RentMapper _rentMapper;
        private readonly IVehicleModelService _vehicleModelService;
        private readonly IManufacturerService _manufacturerService;
        private readonly ICurrencyService _currencyService;

        public RentController(IRentService rentService, RentMapper rentMapper, ILocationService locationService, IClientService clientService, 
            IBranchOfficeService branchOfficeService, IVehicleService vehicleService, IVehicleModelService vehicleModelService, 
            IManufacturerService manufacturerService, ICurrencyService currencyService)
        {
            _rentService = rentService;
            _rentMapper = rentMapper;
            _locationService = locationService;
            _clientService = clientService;
            _branchOfficeService = branchOfficeService;
            _vehicleService = vehicleService;
            _vehicleModelService = vehicleModelService;
            _manufacturerService = manufacturerService;
            _currencyService = currencyService;
        }

        /// <summary>
        /// Prikazuje listu zakupa.
        /// </summary>
        /// <returns></returns>
        [CustomAuthorization]
        public ActionResult Index()
        {
            var rentDomainModels = _rentService.GetAll();
            var rents = _rentMapper.EntityMapper.Map<IList<Rent>>(rentDomainModels);
            foreach (var rent in rents)
            {
                var branchOffice = _branchOfficeService.GetById(rent.OfficeId);
                var location = _locationService.GetById(branchOffice.LocationId);
                rent.Currency = _currencyService.GetById(location.CurrencyId).symbol_native;
                rent.TotalNetAmount = _rentService.CalculateTotalNetAmount(rent._id);
                rent.TotalGrossAmount = _rentService.CalculateTotalGrossAmount(rent._id);
            }
            return View(rents);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var locations = _locationService.GetAll();
            ViewBag.Gradovi = locations.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        });
            return View();
        }

        [HttpPost]
        public JsonResult Create(RentDomainModel model)
        {
            if (ModelState.IsValid)
            {
                var branchOffice = _branchOfficeService.GetById(model.OfficeId);
                var location = _locationService.GetById(branchOffice.LocationId);
                model.Tax = location.Tax;
                _rentService.Save(model);

                if(model.Status == RentStatus.New)
                {
                    var client = _clientService.GetById(model.ClientId.Value);
                    var vehicle = _vehicleService.GetById(model.VehicleId.Value);
                    var vehicleModel = _vehicleModelService.GetById(vehicle.VehicleModelId);
                    var manufacturer = _manufacturerService.GetById(vehicleModel.ManufacturerId);

                    var invoice = new Invoice
                    {
                        RentFrom = model.RentedFrom,
                        RentTo = model.RentedTo,
                        Email = client.Email,
                        OfficeStreet = branchOffice.Street,
                        OfficeName = branchOffice.Name,
                        OfficeTelephone = branchOffice.Telephone,
                        YearOfProduction = vehicle.YearOfProduction,
                        LocationName = location.Name,
                        Name = client.Name,
                        ClientTelephone = client.Telephone,
                        ModelName = vehicleModel.Name,
                        ManufacturerName = manufacturer.Name,
                        RegistrationNumber = vehicle.RegistrationNumber,
                        RentNumber = model.RentNumber,
                        Total = model.TotalNetAmount,
                        PricePerDay = vehicle.PricePerDay,
                        Tax = model.Tax
                    };

                    var email = new Email
                    {
                        To = client.Email,
                        Body = RenderPartialViewToString("Invoice", invoice),
                        Subject = "Potvrda rezervacije"
                    };

                    SendEmail(email, null);
                }

                return Json("OK");
            }

            return Json("ERROR");
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje postojećeg zakupa.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(Guid ID)
        {
            var locations = _locationService.GetAll();
            ViewBag.Gradovi = locations.Select(x =>
                        new SelectListItem
                        {
                            Value = x._id.ToString(),
                            Text = x.Name
                        });
            var model = _rentService.GetById(ID);

            return View(model);
        }

        /// <summary>
        /// Ažurira postojeći zakup.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Edit(RentDomainModel model)
        {
            if (ModelState.IsValid)
            {
                model.Status = RentStatus.NotPaid;
                _rentService.Update(model);
                model.TotalNetAmount = _rentService.CalculateTotalNetAmount(model._id);
                model.TotalGrossAmount = _rentService.CalculateTotalGrossAmount(model._id);
                _rentService.Update(model);

                var client = _clientService.GetById(model.ClientId.Value);
                var branchOffice = _branchOfficeService.GetById(model.OfficeId);
                var location = _locationService.GetById(branchOffice.LocationId);
                var vehicle = _vehicleService.GetById(model.VehicleId.Value);
                var vehicleModel = _vehicleModelService.GetById(vehicle.VehicleModelId);
                var manufacturer = _manufacturerService.GetById(vehicleModel.ManufacturerId);
                var currency = _currencyService.GetById(location.CurrencyId);

                vehicleModel.Status = VehicleStatus.Rented;
                _vehicleModelService.Update(vehicleModel);

                model = _rentService.GetById(model._id);

                var invoice = new Invoice
                {
                    RentFrom = model.RentedFrom,
                    RentTo = model.RentedTo,
                    Email = client.Email,
                    OfficeStreet = branchOffice.Street,
                    OfficeName = branchOffice.Name,
                    OfficeTelephone = branchOffice.Telephone,
                    YearOfProduction = vehicle.YearOfProduction,
                    LocationName = location.Name,
                    Name = client.Name,
                    ClientTelephone = client.Telephone,
                    ModelName = vehicleModel.Name,
                    ManufacturerName = manufacturer.Name,
                    RegistrationNumber = vehicle.RegistrationNumber,
                    RentNumber = model.RentNumber,
                    Total = model.TotalGrossAmount,
                    TotalNetAmount = model.TotalNetAmount,
                    PricePerDay = vehicle.PricePerDay,
                    Tax = location.Tax,
                    Currency = currency.symbol_native
                };

                var email = new Email
                {
                    To = client.Email,
                    Body = RenderPartialViewToString("Invoice", invoice),
                    Subject = "Potvrda rezervacije"
                };

                SendEmail(email, null);


                return Json("OK");
            }
            return Json("ERROR");
        }

        protected string RenderPartialViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;

            using (StringWriter sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }

        /// <summary>
        /// Briše zakup prema ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public JsonResult Delete(Guid ID)
        {
            try
            {
                _rentService.Delete(ID);
            }
            catch
            {

CarStation.Presentation/Views/Home/About.cshtml
@{
    ViewBag.Title = "O nama";
}
<div class="page-header">
    <h2>@ViewBag.Title</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <img src="~/Slike/auta.png" alt="Alternate Text" width="600" class="center-block"/><br />
        <p><b>RentACar</b> je rent a car agencija koju karakteriše kvalitet voznog parka, odlične cijene i korisnički uslovi, kao i susretljivi zaposlenici koji su spremni da odgovore na zahtjeve klijenata, u svakom trenutku. Naše usluge rezervacije vozila nudimo u velikom broju filijala širom BiH.</p>
        <p>Iskreno se nadamo da ćete prepoznati naš kvalitet usluga i postati dio velike grupe naših zadovoljnih klijenata. S druge strane, mi ćemo se dati sve od sebe da opravdamo Vaše povjerenje.</p>
        <p>RentACar tim</p>
    </div>
</div>

CarStation.Presentation/Views/Home/ExistingClient.cshtml
@model CarStation.Presentation.Models.Client


<script type="text/javascript">
    $(document).ready(function () {
        var klijentID = guid();
        var zakupID = guid();
        $('#postojeci-klijent-upit').click(function (e) {
            e.preventDefault();
            $.ajax({
                type: "GET",
                url: "@Url.Action("Details", "Client")",
                data: "Email=" + $('#Email').val(),
                success: function (rezultat) {
                    if (rezultat != "ERROR") {
                        $('#klijent-ime').val(rezultat.Name);
                        $('#klijent-brojLK').val(rezultat.IdentityCard);
                        $('#klijent-brojVD').val(rezultat.DrivingLicense);
                        $('#klijent-telefon').val(rezultat.Telephone);
                        $('#klijent-email').val(rezultat.Email);
                        $('#klijent-email').attr('readonly', 'readonly');
                        klijentID = rezultat._id;

                        $.ajax({
                            type: "GET",
                            url: "@Url.Action("GetAll", "Vehicle")",
                            contentType: 'application/json; charset=utf-8',
                            success: function (rezultat) {
                                $('#VoziloLista').select2({
                                    data: rezultat,
                                    placeholder: "Izaberite vozilo..."
                                });
                            }
                        });
                    }
                }
            });
        });

        $('#kreiraj-Rent').click(function (e) {
            e.preventDefault();

            var url = "@Url.Action("Create", "Rent")?Email=" + $('#Email').val();
            window.location.href = url;

        });
    });
</script>

<div class="form-group margin-top-20">
    <label>Email</label>
    @Html.TextBoxFor(u => u.Email, new { @class = "form-control"})
</div>
<div class="form-group">
    <button type="submit" id="kreiraj-Rent" class="btn btn-primary">Rezerviši</button>
</div>

CarStation.Presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Početna";
}

<script type="text/javascript" src="~/Scripts/helpers.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('body').addClass('pocetna-pozadina');
        $('body').addClass('footer-text');

        PorukeValidacija();

        var zakupID = guid();

        $('#sacuvaj-pocetni-upit').click(function (e) {
            e.preventDefault();
            if ($('#forma-pocetni-upit').valid()) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Create", "Rent")",
                    data: JSON.stringify({
                        RentedFrom: $('#RentedFrom').val(),
                        RentedTo: $('#RentedTo').val(),
                        OfficeId: $('#FilijalaLista').val(),
                        RentNumber: SerijskiBroj(),
                        _id: zakupID
                    }),
                    contentType: 'application/json; charset=utf-8',
                    success: function (rezultat) {
                        if (rezultat == "OK") {
                            var url = @Url.Content("~") + "/Rent/Edit?ID=" + zakupID;
                            window.location.href = url;
                        }
                        else {
                            alert("Došlo je do greške prilikom čuvanja rezervacije.");
                        }

                    }
                });
            }
        });

        $('#postojeci-klijent').addClass('hidden');

        $('#novi-klijent').click(function () {
            $('#novi-klijent').addClass('active');
            $('#klijent-povratnik').removeClass('active');
            $('#pocetni-upit').removeClass('hidden');
            $('#postojeci-klijent').addClass('hidden');
        });

        $('#klijent-povratnik').click(function () {
            $('#klijent-povratnik').addClass('active');
            $('#pocetni-upit').addClass('hidden');
            $('#postojeci-klijent').removeClass('hidden');
            $('#novi-klijent').removeClass('active');
        });

        $("#forma-moj-nalog").validate({
            rules: {
                EmailMojNalog: {
                    required: true,
                    email: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });

        $('#moj-nalog').click(function (e) {
            e.preventDefault();

            var url = "@Url.Action("Edit", "Client")?Email=" + $('#email-moj-nalog').val();
            window.location.href = url;

        });
    });
</script>

<div class="jumbotron margin-top-20">
    <h1>RentACar</h1>
    <p class="lead"><b>RentACar</b> je rent a car agencija koju karakteriše kvalitet voznog parka, odlične cijene i korisnički uslovi, kao i susretljivi zaposlenici koji su spremni da odgovore na zahtjeve klijenata, u svakom trenutku.</p>
    <p><a href="~/Home/About" class="btn btn-primary btn-lg">Više &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="panel dark-panel panel-default">
            <div class="panel-body">
                <h2>Rezervacija</h2>
                <ul class="nav nav-tabs">
                    <li class="active" id="novi-klijent"><a href="#">Novi klijent</a></li>
                    <li id="klijent-povratnik"><a href="#">Postojeći klijent</a></li>
                </ul>
                <div id="pocetni-upit">
                    @{Html.RenderPartial("Query");}
                </div>
                <div id="postojeci-klijent">
                    @{Html.RenderPartial("ExistingClient");}
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel dark-panel panel-default">
            <div class="panel-body">
                <h2>Moj nalog</h2>
                <form id="forma-moj-nalog">
                    <div class="form-group margin-top-20">
                        <label class="standardni-font">Email</label>
                        <input type="email" name="EmailMojNalog" id="email-moj-nalog" class="form-control" />
                    </div>
                    <div class="form-group">
                        <button type="submit" id="moj-nalog" class="btn btn-primary">Potvrdi</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

CarStation.Presentation/Views/Home/Query.cshtml
@model CarStation.Domain.Models.RentDomainModel

<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />

<script type="text/javascript">
    $(document).ready(function () {

        $('#GradLista').select2({
            placeholder: "Izaberite lokaciju..."
        }).on("change", function () {
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetByCity", "BranchOffice")",
                data: "ID=" + $("#GradLista").val(),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    $('#FilijalaLista').empty();
                    $('#FilijalaLista').select2({ data: rezultat, placeholder: "Filijale..." });

                }
            });
        });

        $("#RentedFrom").datepicker({
            dateFormat: "dd-MM-yy",
            minDate: 'today',
            maxDate: "+90D",
            onSelect: function (selected) {
                $("#RentedTo").datepicker("option", "minDate", selected);
            }
        });

        $("#RentedTo").datepicker({
            dateFormat: "dd-MM-yy",
            minDate: 'today',
            maxDate: "+90D",
            onSelect: function (selected) {
                $("#RentedFrom").datepicker("option", "maxDate", selected);
            }
        });

        if ($('#GradLista').val() != "") {
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetByCity", "BranchOffice")",
                data: "ID=" + $("#GradLista").val(),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat.length > 0) {
                        $('#FilijalaLista').select2({ data: rezultat, placeholder: "Filijale..." });
                    }

                }
            });
        }

        $("#forma-pocetni-upit").validate({
            rules: {
                RentedFrom: {
                    required: true
                },
                RentedTo: {
                    required: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });
    
</script>

@using (Html.BeginForm("Create", "Rent", FormMethod.Post, new { @id = "forma-pocetni-upit" }))
{
    @Html.ValidationSummary(true, "Rezervacija nije uspjela.");

        <fieldset class="margin-top-20">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="editor-label">
                        <label class="standardni-font">Lokacija</label>
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("LocationId", (IEnumerable<SelectListItem>)ViewBag.Gradovi, new { @id = "GradLista", @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="editor-label">
                        <label class="standardni-font">Filijala</label>
                    </div>
                    <div class="editor-field">
                        <select id="FilijalaLista" class="form-control"></select>
                        @*@Html.DropDownListFor(u => u.FilijalaID, (IEnumerable<SelectListItem>)ViewBag.Gradovi, new { @class = "form-control" })*@
                        @Html.ValidationMessageFor(u => u.OfficeId, null, new { @class = "inline-help error" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="editor-label">
                        <label class="standardni-font">Polazak</label>
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(u => u.RentedFrom, new { @class = "form-control" })
                        @Html.ValidationMessageFor(u => u.RentedFrom, null, new { @class = "inline-help error" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="editor-label">
                        <label class="standardni-font">Povratak</label>
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(u => u.RentedTo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(u => u.RentedTo, null, new { @class = "inline-help error" })
                    </div>
                </div>
            </div>
    </fieldset>
}
<div class="form-group">
    <input class="btn btn-primary" id="sacuvaj-pocetni-upit" value="Rezerviši" />
</div>